### ISSUE TITLE
firefox-kde out-of-dated

### ISSUE THREAD

**Issue by francoism90** [FadeMind/archpkgbuilds#1]
See: https://ftp.mozilla.org/pub/firefox/releases/44.0.2/source/

Thanks! :)

**Comment by FadeMind** [comment]
https://github.com/FadeMind/archpkgbuilds/commit/29d576742aacd816a3188cd66b75bd3baf707014

**Comment by francoism90** [comment]
Thanks for the update, unfortunately it doesn't build:
js/src> creating ./config.status
js/src> /bin/sh: ./config.status: /mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/ob: bad interpreter: No such file or directory

*** Fix above errors and then restart with\
               "make -f client.mk build"
/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/client.mk:359: recipe for target 'configure' failed
make[3]: *** [configure] Error 1
make[3]: Leaving directory '/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2'
/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/client.mk:373: recipe for target '/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/obj-x86_64-unknown-linux-gnu/Makefile' failed
make[2]: *** [/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/obj-x86_64-unknown-linux-gnu/Makefile] Error 2
make[2]: Leaving directory '/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2'
/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2/client.mk:228: recipe for target 'profiledbuild' failed
make[1]: *** [profiledbuild] Error 2
make[1]: Leaving directory '/mnt/data/tmp/archpkgbuilds/AUR/mozilla-kde/firefox-kde/src/firefox-44.0.2'
client.mk:171: recipe for target 'build' failed
make: *** [build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by FadeMind** [comment]
1. You need to using clean chroot environment. (AUR: [clean-chroot-manager](https://aur.archlinux.org/packages/clean-chroot-manager/) )
2. You need care about proper CFLAGS /CXXFLAGS in `makepkg.conf`.
3. Formaly this PKGBUILD is copy from: [Manjaro Community GH](https://github.com/manjaro/packages-community/tree/master/firefox-kde)

**Comment by francoism90** [comment]
Thanks, that did the trick! :D
